### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './data/ids.json'

### ISSUE THREAD

**Issue by yupeijei1997** [seanie12/CLAPS#2]
Hi，

When I was doing data preprocessing, I encountered the following error. Could you please provide this json file?

Thank you！

```FileNotFoundError: [Errno 2] No such file or directory: './data/ids.json'```

**Comment by seanie12** [comment]
Hi, I am sorry for missing the file.

I upload the file [here](https://drive.google.com/file/d/1gWpwacqdcFYpyTOXmdJyTqhzmzpIDhAo/view?usp=sharing).

You can download the original file from this [repository](https://github.com/EdinburghNLP/XSum/blob/master/XSum-Dataset/XSum-TRAINING-DEV-TEST-SPLIT-90-5-5.json). 

As far as I know they are identical file.

**Comment by yupeijei1997** [comment]
Thank you！

I have successfully preprocessed the summarization data.
