### ISSUE TITLE
can not download the data 

### ISSUE THREAD

**Issue by crazyseabiscuit** [seanie12/CLAPS#6]
Hi 
 i am trying to download the model and data file of question generation from your google drive address 
https://drive.google.com/file/d/1TpohA_frUOM-G4W2kUDjd0mztRPtpemp/view?usp=sharing but it seems loading forever... is there any other place i can get these file?

**Comment by seanie12** [comment]
I don't know what's causing the problem, but I can still access to the google drive. If you send me an email, I can share the file via email. Thanks

**Comment by crazyseabiscuit** [comment]
thanks for the quick response , it seems something wrong with my google account ,  i get the data and model for QG now , pls feel free to close this.
